
export const ACTION_PREFIX = '@@api/';

export const FETCH_REQUEST_START = `${ACTION_PREFIX}/FETCH_REQUEST_START`;
export const FETCH_REQUEST_SUCCESS = `${ACTION_PREFIX}/FETCH_REQUEST_SUCCESS`;
export const FETCH_REQUEST_FAILURE = `${ACTION_PREFIX}/FETCH_REQUEST_FAILURE`;
export const ADD_DATA_CONSUMER = `${ACTION_PREFIX}/ADD_DATA_CONSUMER`;
export const REMOVE_DATA_CONSUMER = `${ACTION_PREFIX}/REMOVE_DATA_CONSUMER`;